import fs from 'node:fs';import vm from 'node:vm';import {spawnSync} from 'node:child_process';
const files=['assets/js/v88-deep-lessons-data.js','assets/js/v88-engine.js','assets/js/v88-ui.js','assets/css/v88-deep.css','release-v8.8.json','index.html','manifest.webmanifest','service-worker.js'];let failed=0;const ok=(n,d='')=>console.log(`PASS ${n}${d?` — ${d}`:''}`),bad=(n,d='')=>{failed++;console.error(`FAIL ${n}${d?` — ${d}`:''}`)};
for(const f of files)fs.existsSync(f)?ok('file',f):bad('file',f);
for(const f of files.filter(x=>x.endsWith('.js'))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});r.status===0?ok('syntax',f):bad('syntax',r.stderr)}
try{const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/v88-deep-lessons-data.js','utf8'),c);const d=c.window.LGMK_V88_DATA;d.lessons.length===30?ok('lesson count','30'):bad('lesson count',d.lessons.length);new Set(d.lessons.map(x=>x.courseId)).size===10?ok('course coverage','10'):bad('course coverage');d.submissionChecklist.length===13?ok('checklist count','13'):bad('checklist count',d.submissionChecklist.length);d.submissionChecklist.filter(x=>x.required).length===12?ok('required gates','12'):bad('required gates')}catch(e){bad('data evaluation',e.message)}
const idx=fs.readFileSync('index.html','utf8');for(const t of ['Legal German MasterKit v8.8.0','v88-deep-lessons-data.js?v=880','v88-engine.js?v=880','v88-ui.js?v=880','v88-deep.css?v=880','id="deepLessons"','id="citationBuilder"','id="submissionPackage"'])idx.includes(t)?ok('index',t):bad('index',t);
const rel=JSON.parse(fs.readFileSync('release-v8.8.json','utf8'));rel.lessons===30?ok('release lessons','30'):bad('release lessons');rel.submission?.required_gates===12?ok('release gates','12'):bad('release gates');
const man=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));man.name.includes('v8.8.0')?ok('manifest',man.name):bad('manifest',man.name);
const sw=fs.readFileSync('service-worker.js','utf8');for(const t of ['lgmk-v8-8-deep-submission','release-v8.8.json','v88-deep.css?v=880','v88-deep-lessons-data.js?v=880','v88-engine.js?v=880','v88-ui.js?v=880'])sw.includes(t)?ok('cache',t):bad('cache',t);
if(failed)process.exit(1);console.log('\nAll v8.8 quality gates passed.');